#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN_BASE_PATH="$PLUGIN_CORE_AVAILABLE_PATH"

source "$PLUGIN_BASE_PATH/common/functions"
source "$PLUGIN_PATH/pushover_dokku_defines"
source "$PLUGIN_PATH/pushover_dokku_functions"

case "$1" in
  ${PLUGIN_COMMAND_PREFIX}:create)
    create_pushover_service
    ;;
  ${PLUGIN_COMMAND_PREFIX}:set)
    set_pushover_settings
    ;;

  ${PLUGIN_COMMAND_PREFIX}:clear)
    clear_pushover_settings
    ;;

  ${PLUGIN_COMMAND_PREFIX}:get)
    get_pushover_settings
    ;;

  help | ${PLUGIN_COMMAND_PREFIX}:help)
	  get_pushover_help
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;
esac