#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$0")/pushover_dokku_defines"

# Pull down the docker image if needed
#if ! docker images | grep -e "^$PLUGIN_IMAGE " | grep -q "$PLUGIN_IMAGE_VERSION" ; then
#  docker pull "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION"
#fi

# Create the plugin root folder
#mkdir -p "$PLUGIN_DATA_ROOT" || echo "Failed to create $PLUGIN_SERVICE directory"
#chown dokku:dokku "$PLUGIN_DATA_ROOT"

git clone https://github.com/kruffin/dokku-pushover-dockerfiles.git /tmp/dokku-pushover-dockerfiles
docker build -t kruffin/pushover /tmp/dokku-pushover-dockerfiles
rm -rf /tmp/dokku-pushover-dockerfiles